"""create cases table

Revision ID: 158007032ff7
Revises: 
Create Date: 2025-10-25 22:51:22.689982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158007032ff7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('court_name', sa.String(length=255), nullable=False),
    sa.Column('case_number', sa.String(length=255), nullable=False),
    sa.Column('case_proc', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('judge', sa.String(length=255), nullable=True),
    sa.Column('judges', sa.Text(), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('stage_date', sa.Date(), nullable=True),
    sa.Column('stage_name', sa.String(length=255), nullable=True),
    sa.Column('cause_result', sa.Text(), nullable=True),
    sa.Column('cause_dep', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
